Jacqueline/my toys
plentymarkets/manual pull request #1738
Opened 2021-06-21 11:03 UTC by jawendel

2021-06-22 06:10 UTC, dbohla requested changes

2021-06-22 06:39 UTC, jawendel commented on de/maerkte/mytoys.adoc
> +:keywords: myToys, mytoys, toys, Marktplatz, mytoys einrichten, mytoys Marktplatz, Multi-Channel, Multichannel, Multi-Channel mytoys, Multichannel mytoys, Multi Channel mytoys
Keywords füge ich hinzu, kein Problem. Können auch noch weitere einfügen, wenn euch welche einfallen.

2021-06-22 06:41 UTC, jawendel commented on de/maerkte/mytoys.adoc
> +* Deine Produkte werden im myToys Marktplatz gelistet. Der Name deines Unternehmens wird an deinen Produkten angezeigt.
Ok, dann nehme ich den zweiten Satz raus.

2021-06-22 06:43 UTC, jawendel commented on de/maerkte/mytoys.adoc
> +//Gibt es hier vielleicht doch noch etwas Genaueres, das wir angeben können?
Ok, danke dir. Schaue mal, dass ich das noch ein bisschen anpasse.

2021-06-23 10:00 UTC, dbohla requested changes

2021-06-23 10:24 UTC, jawendel commented on de/maerkte/mytoys.adoc
> +*_Hinweis:_* Kund:innen zahlen an myToys. Deshalb werden alle Aufträge mit dem Status *[5] Bezahlt* importiert.
Alles klar, füge ich hinzu.

2021-06-23 10:29 UTC, jawendel commented on de/maerkte/mytoys.adoc
> +|====
Nehme ich auf.

2021-06-23 10:30 UTC, jawendel commented on de/maerkte/mytoys.adoc
> +|*UVP*
Füge ich ebenfalls hinzu.

2021-07-01 06:31 UTC, merged