Added information about variations and credit notes
plentymarkets/manual pull request #2683
Opened 2021-12-16 10:20 UTC by snawratil

2021-12-16 13:16 UTC, jschaakplenty requested changes

2021-12-16 13:16 UTC, jschaakplenty commented on de/maerkte/cdiscount.adoc
> +Bei Varianten, die auf CDiscount als Variantenartikel eingestellt sind, werden Attribute nicht an den Produktnamen angehängt.
```suggestion
Bei Varianten, die auf Cdiscount als Variantenartikel eingestellt sind, werden Attribute nicht an den Produktnamen angehängt.
```

2021-12-16 13:16 UTC, jschaakplenty commented on de/maerkte/cdiscount.adoc
> +Ein:e Kund:in bestellt einen Pullover für 30€ und eine Jacke für 50€ und retourniert die Jacke. Bei Cdiscount wird eine Gutschrift für alle Auftragspositionen erstellt, also in diesem Fall für 80€.
Not correct.

A better example:

You buy one pullover for €30 each (€60 total) and one jacket for €50.
The customer returns one of the pullovers and you create a return and use that to notify Cdiscount of the return.
Cdiscount will now refund €60 because it is not possible to define the quantity, so they will assume both have to be refunded.

2021-12-17 08:59 UTC, snawratil commented on de/maerkte/cdiscount.adoc
> +Ein:e Kund:in bestellt einen Pullover für 30€ und eine Jacke für 50€ und retourniert die Jacke. Bei Cdiscount wird eine Gutschrift für alle Auftragspositionen erstellt, also in diesem Fall für 80€.
done

2021-12-17 09:01 UTC, merged