Update otto-market.adoc
plentymarkets/manual pull request #941
Opened 2021-01-11 14:13 UTC by khoffmeister

2021-01-11 14:32 UTC, mariusbippig requested changes

2021-01-11 14:32 UTC, mariusbippig commented on de/maerkte/otto/otto-market.adoc
> +* *Alternativer Retouren-Versanddienstleister* = Einen Versanddienstleister aus der angezeigten Dropdown-Liste wählen. Dieser feste Versanddienstleister wird für alle Sendungen verwendet, die über di
Einen Versanddienstleister aus der angezeigten Dropdown-Liste wählen. Dieser feste Versanddienstleister wird für alle Sendungen verwendet.

2021-01-11 14:32 UTC, mariusbippig commented on de/maerkte/otto/otto-market.adoc
> +* *Keinen alternativen Retouren-Versanddienstleister verwenden* = Es wird gar kein Versanddienstleister für Retouren zugeordnet.
Es wird nicht versucht einen alternativen Retouren-Versanddienstleister zu ermitteln.

2021-01-12 15:28 UTC, khoffmeister commented on de/maerkte/otto/otto-market.adoc
> +* *Alternativer Retouren-Versanddienstleister* = Einen Versanddienstleister aus der angezeigten Dropdown-Liste wählen. Dieser feste Versanddienstleister wird für alle Sendungen verwendet, die über di
aktualisiert

2021-01-12 15:28 UTC, khoffmeister commented on de/maerkte/otto/otto-market.adoc
> +* *Keinen alternativen Retouren-Versanddienstleister verwenden* = Es wird gar kein Versanddienstleister für Retouren zugeordnet.
aktualisiert

2021-01-13 08:59 UTC, mariusbippig approved these changes

2021-01-13 14:17 UTC, merged